[sdk]
    [sdk.log]
        # 当前支持日志级别: "trace", "debug", "info", "warn", "error", "fatal", "panic"
        level = "debug"
        # 日志文件名称
        filename = "alidts.log"
        # 日志结转配置
        [sdk.log.rotate]
            # 日志最大保存时间7天(单位hour)
            max_age = 168
            # 日志切割时间间隔24小时（单位hour)
            rotation_time=24
    [sdk.kafka]
        [[sdk.kafka.items]]
            name = "aliyun"
            brokers=["127.0.0.1:18003"]
            [[sdk.kafka.items.consumers]]
                name = "syncsomething"
                username = "testuser"
                password = "testpassword"
                group_id = "testgroup"
                topic = "testtopic"
